### ISSUE TITLE
gitlab-ce和 sameersbn/gitlab主要区别是啥

### ISSUE THREAD

**Issue by fengjie926** [get-set/infra-docker-compose#2]
提问,非 issue.

我看其他人 compose 多数用的是sameersbn/gitlab ,这个 image依赖一个操作系统 ,image本身都 过 G 了

您使用的这个 gitlab-ce 是否也是如此,只是内部集成了 数据库和 redis 吗

然后:
volumes:
  gitlab-config:
    name: gitlab-config
  gitlab-logs:
    name: gitlab-logs
  gitlab-data:
    name: gitlab-data

这些 逻辑卷 在 宿主机上好像并不可见,咋才能备份呢?

**Comment by kangeek** [comment]
“gitlab/gitlab-ce”是gitlab官方提供的镜像，“sameersbn/gitlab”这个镜像我没有研究过，不过可以通过代码库（https://github.com/sameersbn/docker-gitlab）了解到他都打包了哪些东西，在docker hub上面的下载量挺可观的，所以估计也还是不错的~ 
命名的volume可以在`/var/lib/docker/volumes`下面找到。

**Comment by fengjie926** [comment]
根据 docker volume inspect 可以看出在宿主机的: /var/lib/docker/volumes下,但奇怪真实却不存在

1.查看 docker volume
docker volume ls
DRIVER    VOLUME NAME
local     gitlab-config
local     gitlab-data
local     gitlab-logs

2. docker volume inspect gitlab-data
[
    {
        "CreatedAt": "2021-08-02T12:57:18Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "liunx",
            "com.docker.compose.version": "1.29.2",
            "com.docker.compose.volume": "gitlab-data"
        },
        "Mountpoint": "/var/lib/docker/volumes/gitlab-data/_data",
        "Name": "gitlab-data",
        "Options": null,
        "Scope": "local"
    }
]

3.cd /var/lib/doker/volumes
cd: no such file or directory: /var/lib/doker/volumes

宿主机上无法找到此文件.... 莫非是在 docker deamon 里面?

gitlab 的 volumes 好像并没有其他的 container 共享,为何不用如下 更为直接的方式呢?
../config:/etc/gitlab:Z \
../logs:/var/log/gitlab:Z \
../data:/var/opt/gitlab:Z \

然后 gitlab.rb 为何 不跟 Nginx 的 config.d目录一样 ,映射到外面管理呢?

**Comment by kangeek** [comment]
`cd: no such file or directory: /var/lib/doker/volumes`
是不是因为这个`docker`写错了

**Comment by fengjie926** [comment]
/var/lib/doker/volumes,

这个确实是写错了不好意思.

发现在 MAC OS 上  :
var/lib 下只有 , postfix 目录.没有 docker 目录. 可能 MAC OS 不太一样,这个就不纠结了.

在centos 上确实存在该目录./var/lib/docker/volumes

如果备份的话,你一般咋做的, 是 直接备份该目录里面的 data 吗? 还是使用应用程序的备份功能.

**Comment by kangeek** [comment]
备份的话，可以把`/var/lib/docker/volumes`目录挂载到高可用的分布式存储上，也可以针对具体的目录进行同步或定期备份。应用也可以用HA的方案部署。

前面还有个问题就是为什么用命名卷而不是用主机目录映射的方式，其实都是可以的，如果有配置文件需要挂载到容器中，而配置文件又是代码版本管理的一部分，那么就可以做目录映射，比如nginx的`config.d`目录。不过目录映射可能会需要处理文件权限问题，尤其是不以root用户管理容器的时候。

**Comment by fengjie926** [comment]
感谢感谢
