### ISSUE TITLE
请教关于容器的 IP 及 hostst 配置

### ISSUE THREAD

**Issue by fengjie926** [get-set/infra-docker-compose#3]
readme中有如下描述:

_/etc/dnsmasq.hosts，配置内网域名解析，内容如下：
# ops
172.31.0.254    dns ntp dns.example.com ntp.example.com
172.31.0.253    nas nas.example.com
172.31.3.101    vcenter vcenter.example.com
172.23.0.101    jira jira.example.com_

大佬好,依然是请教问题:

docker-compose 中并未显示定义各个容器的的 IP4 地址 (ipv4_address: 未配置), 这里为何能直接这样写呢?

docker-compose 中hostname: 的配置 是 可以让在同一个网络中的其他容器直接通过 hostname:端口的形式访问吗?

**Comment by kangeek** [comment]
大佬不敢当。
这里其实就是搭建了一个研发内网所用的DNS，可以配置到内网的网络设备上。
这个配置文件里的IP实际上是所在主机的IP，根据你的实际情况调整就可以。
同一个docker-compose网络中的不同service可以通过`service.name`给定的名字互相访问，不过跨主机是不行的，所以需要搭一个内部的DNS。如果你对K8S熟悉的话，可以利用K8S的service来进行流量的转发。

**Comment by fengjie926** [comment]
好的 感谢答复.
明白了, 代码中例子是都部署在一台主机上. readme 中是示例根据情况调整 dns 服务的域名 ip 的配置.

一般内网路由是专门小组或部门管理,如果无法协调内部 dns, 那就只能是 麻烦一点用的人都改 hosts 是吧
